services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DOMAIN=lovosis.in
      - NEXTAUTH_URL=https://lovosis.in
    restart: always 