services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DOMAIN=lovosis.in
      - NEXTAUTH_URL=https://lovosis.in
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SKIP_BUILD_STATIC_GENERATION=true
    volumes:
      - ./.next/static/videos:/app/.next/static/videos:rw
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true 